<?php
/**
 * Generate chrysoberyl-en_US.po from .pot with English translations for Thai strings.
 * Run from theme root: php make-en-po.php
 */
$theme_dir = __DIR__;
$pot_file  = $theme_dir . '/languages/chrysoberyl.pot';
$po_file   = $theme_dir . '/languages/chrysoberyl-en_US.po';

$map = array(
    '% ความคิดเห็น' => '% comments',
    '0 ความคิดเห็น' => '0 comments',
    '1 ความคิดเห็น' => '1 comment',
    'Auto-collapse on Mobile (ย่ออัตโนมัติบนมือถือ)' => 'Auto-collapse on Mobile',
    'Bottom (ด้านล่าง)' => 'Bottom',
    'Button Style (สไตล์ปุ่ม)' => 'Button Style',
    'Categories (หมวดหมู่)' => 'Categories',
    'Collapsible (ย่อ/ขยายได้)' => 'Collapsible',
    'Collapsible Menu (เมนูย่อ/ขยาย)' => 'Collapsible Menu',
    'Content (เนื้อหา)' => 'Content',
    'Date (เก่าสุด)' => 'Date (oldest first)',
    'Date (ใหม่สุด)' => 'Date (newest first)',
    'Dropdown (ใต้ search box)' => 'Dropdown (below search box)',
    'Excerpt (คำอธิบาย)' => 'Excerpt',
    'Floating (ลอยด้านข้าง)' => 'Floating',
    'Floating Button (ปุ่มลอย)' => 'Floating Button',
    'H2 (หัวข้อหลัก)' => 'H2 (main heading)',
    'H3 (หัวข้อย่อย)' => 'H3 (subheading)',
    'H4 (หัวข้อรอง)' => 'H4 (secondary heading)',
    'Icon + Text (ไอคอนและข้อความ)' => 'Icon + Text',
    'Icon Only (ไอคอนเท่านั้น)' => 'Icon Only',
    'Large (ใหญ่)' => 'Large',
    'Medium (กลาง)' => 'Medium',
    'Nested/Indented (แบบซ้อน)' => 'Nested/Indented',
    'Numbered List (รายการแบบมีเลข)' => 'Numbered List',
    'Relevance (ความเกี่ยวข้อง)' => 'Relevance',
    'Sidebar (ด้านข้าง)' => 'Sidebar',
    'Simple List (รายการธรรมดา)' => 'Simple List',
    'Small (เล็ก)' => 'Small',
    'Smooth Scroll (เลื่อนแบบนุ่มนวล)' => 'Smooth Scroll',
    'Sticky (ติดตามเมื่อ scroll)' => 'Sticky',
    'Tags (ป้ายกำกับ)' => 'Tags',
    'Title (ชื่อบทความ)' => 'Title',
    'Top (ด้านบน)' => 'Top',
    'Top (ด้านบนเนื้อหา)' => 'Top (above content)',
    'กริด (th-large)' => 'Grid (th-large)',
    'กลับขึ้นด้านบน' => 'Back to top',
    'กลับหน้าก่อนหน้า' => 'Go back',
    'กลับหน้าแรก' => 'Back to home',
    'กองบรรณาธิการ' => 'Editorial Team',
    'กาเหว่า' => 'Gawao',
    'ก่อนหน้า' => 'Previous',
    'ขนาด:' => 'Size:',
    'ขออภัย ไม่พบเนื้อหาที่คุณกำลังมองหา ลองค้นหาด้วยคำอื่น' => 'Sorry, no content found. Try another search.',
    'ข่าวที่เกี่ยวข้อง' => 'Related News',
    'ข่าวน่าสนใจ' => 'Interesting News',
    'ข่าวล่าสุด' => 'Latest News',
    'ข้อความด้านซ้ายของแถบ copyright (เว้นว่าง = ใช้ค่าเริ่มต้น). ใช้ {year} สำหรับปี, {sitename} สำหรับชื่อเว็บ' => 'Text on the left of the copyright bar (leave empty for default). Use {year} for year, {sitename} for site name',
    'ข้อความที่ต้องการให้แสดงเมื่อแชร์ (ใช้ {title} สำหรับชื่อบทความ, {url} สำหรับลิงก์)' => 'Text to show when sharing (use {title} for post title, {url} for link)',
    'ข้อความที่แสดงใน Search Box' => 'Text displayed in Search Box',
    'ข้อความหัวข้อ:' => 'Heading text:',
    'ข้อมูล (info-circle)' => 'Info (info-circle)',
    'ความคิดเห็น' => 'Comments',
    'ความยาวขั้นต่ำของคำค้นหา (1-10 ตัวอักษร)' => 'Minimum search term length (1-10 characters)',
    'ความเห็น' => 'Comments',
    'คอลัมน์' => 'columns',
    'คำค้นยอดฮิต:' => 'Popular searches:',
    'ค้นหา' => 'Search',
    'ค้นหา...' => 'Search...',
    'ค้นหาข่าว' => 'Search news',
    'ค้นหาข่าวและเทรนด์ล่าสุด' => 'Search news and latest trends',
    'จะแสดงปุ่มโซเชียล (Facebook, Twitter, Instagram, YouTube). ลิงก์ปัจจุบันเป็นตัวอย่าง (#). ถ้าต้องการกำหนด URL จริง ให้เลือก "Sidebar (Widgets)" แล้วไปที่ Appearance → Widgets → Footer นี้ แล้วใส่ Widget "Chrysoberyl: Social Follow" แล้วกรอกลิงก์ใน Widget' => 'Shows social buttons (Facebook, Twitter, Instagram, YouTube). Current links are placeholders (#). To set real URLs, choose "Sidebar (Widgets)" and go to Appearance → Widgets → this Footer, then add "Chrysoberyl: Social Follow" widget and enter links there.',
    'จำนวน Heading ขั้นต่ำที่จะแสดง TOC (0 = แสดงเสมอ)' => 'Minimum headings to show TOC (0 = always show)',
    'จำนวน Suggestions ที่แสดง (1-20)' => 'Number of suggestions to show (1-20)',
    'จำนวนคอลัมน์ข่าวล่าสุด (หน้าแรก)' => 'Number of latest news columns (homepage)',
    'ชื่อหัวข้อของ TOC (เช่น: สารบัญ, Table of Contents)' => 'TOC heading title (e.g. Table of Contents)',
    'ช่องค้นหาใน sidebar' => 'Search box in sidebar',
    'ดาว (star)' => 'Star (star)',
    'ดูทั้งหมด' => 'View all',
    'ดูบทความทั้งหมด' => 'View all posts',
    'ดูเหมือนว่าเราไม่พบสิ่งที่คุณกำลังมองหา ลองค้นหาดู' => 'It seems we can\'t find what you\'re looking for. Try searching.',
    'ด้านข้างหน้าจอ' => 'Side of screen',
    'ด้านบนบทความ' => 'Above post',
    'ด้านล่างบทความ' => 'Below post',
    'ตั้งค่า Table of Contents (TOC) สำหรับบทความ' => 'Configure Table of Contents (TOC) for posts',
    'ตั้งค่าการค้นหาและ Search Suggestions' => 'Configure search and Search Suggestions',
    'ตั้งค่าการแชร์เนื้อหาไปยัง Social Media platforms ต่างๆ' => 'Configure sharing content to Social Media platforms',
    'ตำแหน่ง (map-marker-alt)' => 'Location (map-marker-alt)',
    'ติดตาม' => 'Subscribe',
    'ติดตามข่าวสารและอัปเดตล่าสุด' => 'Subscribe for latest news and updates',
    'ติดตามเรา' => 'Follow us',
    'ติดต่อโฆษณา' => 'Advertise with us',
    'ต้นกล้าไอที' => 'Tonkla IT',
    'ถัดไป' => 'Next',
    'ถ้าไม่ใส่โค้ด จะแสดงกรอบ placeholder โฆษณา' => 'If no code is entered, an ad placeholder will be shown',
    'ถ้าไม่ใส่โค้ด จะแสดงกรอบ placeholder โฆษณาให้' => 'If no code is entered, an ad placeholder will be shown',
    'ทีมผู้พัฒนา:' => 'Development team:',
    'ที่คั่น (bookmark)' => 'Bookmark (bookmark)',
    'ที่แล้ว' => 'ago',
    'ธีม Chrysoberyl พัฒนาและดูแลโดย' => 'Chrysoberyl theme developed and maintained by',
    'ธีมนี้ใช้งานได้ฟรี ตามเงื่อนไขสัญญาอนุญาตของ WordPress (GPL)' => 'This theme is free to use under the WordPress (GPL) license.',
    'ธีม Trend Today' => 'Trend Today theme',
    'ฟอร์กมาจาก:' => 'Forked from:',
    'เว็บที่ใช้งานจริง:' => 'Live site:',
    'นโยบายความเป็นส่วนตัว' => 'Privacy Policy',
    'บทความ' => 'Posts',
    'บทความที่มีความเห็นมาก' => 'Posts with most comments',
    'บทความที่มีความเห็นมากที่สุด' => 'Posts with most comments',
    'บทความที่เกี่ยวข้อง' => 'Related posts',
    'บทความที่เกี่ยวข้องตามหมวดหมู่/แท็ก (เหมาะกับหน้า single)' => 'Related posts by category/tag (best on single post)',
    'ปรับแต่งส่วน footer: newsletter, tags, คอลัมน์ widget และข้อความ copyright' => 'Customize footer: newsletter, tags, widget columns and copyright text',
    'ปิด = แสดงหน้าเข้าสู่ระบบแบบดั้งเดิมของ WordPress' => 'Off = show default WordPress login page',
    'ปิดใช้ถ้าต้องการให้บทความเต็มความกว้างโดยไม่มี sidebar ด้านขวา' => 'Turn off to make single post full width without right sidebar',
    'ปิดใช้ถ้าต้องการให้หน้า Archive (หมวดหมู่, แท็ก, ผู้เขียน ฯลฯ) เต็มความกว้างโดยไม่มี widget ด้านขวา' => 'Turn off to make Archive pages full width without right widget area',
    'ปิดใช้ถ้าต้องการให้หน้าคงที่เต็มความกว้างโดยไม่มี sidebar ด้านขวา' => 'Turn off to make Pages full width without right sidebar',
    'ปิดใช้ถ้าต้องการให้หน้าแรกเต็มความกว้างโดยไม่มี widget ด้านขวา (Popular Posts, Recent Posts, Trending Tags)' => 'Turn off to make homepage full width without right widgets (Popular Posts, Recent Posts, Trending Tags)',
    'ปิดใช้ถ้าไม่ต้องการให้มีปุ่มแชร์ในหน้าคงที่' => 'Turn off to hide share buttons on pages',
    'ปิดใช้ถ้าไม่ต้องการให้มีปุ่มแชร์ในหน้าบทความ' => 'Turn off to hide share buttons on single post',
    'ปุ่มติดตาม Facebook, Twitter, Line, YouTube ฯลฯ' => 'Follow buttons for Facebook, Twitter, Line, YouTube, etc.',
    'ผลการค้นหา' => 'Search results',
    'ผลการค้นหาสำหรับ %s' => 'Search results for %s',
    'ผู้ใช้' => 'Users',
    'พร้อมที่จะเผยแพร่โพสต์แรกของคุณแล้ว? <a href="%1$s">เริ่มที่นี่</a>.' => 'Ready to publish your first post? <a href="%1$s">Get started here</a>.',
    'พิมพ์คำค้นหา...' => 'Type to search...',
    'พื้นที่โฆษณาหรือ HTML กำหนดเอง' => 'Ad or custom HTML area',
    'มาแรง:' => 'Trending:',
    'ยอดนิยม' => 'Popular',
    'ยังไม่มีบทความ' => 'No posts yet',
    'ระยะเวลาที่รอก่อนค้นหา (0-2000ms, แนะนำ 300ms)' => 'Delay before searching (0-2000ms, 300ms recommended)',
    'รายการ' => 'Items',
    'รายการ (list)' => 'List (list)',
    'รายการหมวดหมู่พร้อมจำนวนบทความ' => 'Category list with post count',
    'ร่วมงานกับเรา' => 'Join us',
    'ลองค้นหาดู...' => 'Try searching...',
    'ลองใช้คำค้นหาอื่น หรือตรวจสอบการสะกด' => 'Try different keywords or check spelling',
    'ลากเพื่อเรียงลำดับการแสดงผล • เลือกติ๊กเพื่อเปิดใช้' => 'Drag to reorder • Tick to enable',
    'ลิงก์ (link)' => 'Link (link)',
    'ลูกศร (chevron-right)' => 'Arrow (chevron-right)',
    'วิธีใส่โค้ด:' => 'How to add code:',
    'สมัครรับข่าวสาร' => 'Subscribe to newsletter',
    'สมัครรับข่าวสารสรุปประจำวันส่งตรงถึงอีเมลของคุณ' => 'Subscribe to daily digest delivered to your email',
    'สมุดที่อยู่ (address-book)' => 'Address book (address-book)',
    'สารบัญ' => 'Table of Contents',
    'หน้า' => 'Pages',
    'หน้านี้อาจถูกลบหรือย้ายไปที่อื่นแล้ว' => 'This page may have been removed or moved',
    'หน้าเข้าสู่ระบบ (Login)' => 'Login page',
    'หน้าแรก' => 'Home',
    'หมวดหมู่' => 'Categories',
    'หมายเหตุ:' => 'Note:',
    'หัวข้อและไอคอน' => 'Heading and icon',
    'หัวใจ (heart)' => 'Heart (heart)',
    'อัปเดตเมื่อ %s' => 'Updated on %s',
    'อาร์คิฟ' => 'Archive',
    'อาร์คิฟแยกตามเดือน' => 'Monthly archive',
    'อีเมล (envelope)' => 'Email (envelope)',
    'อ่าน %d นาที' => '%d min read',
    'เกี่ยวกับธีม' => 'About theme',
    'เกี่ยวกับเรา' => 'About us',
    'เขียนบทความใหม่' => 'Write new post',
    'เงื่อนไขการใช้งาน' => 'Terms of Service',
    'เช่น หมวดหมู่, เกี่ยวกับเรา' => 'e.g. Categories, About us',
    'เนื้อหา: ไปที่ Appearance → Widgets แล้วเลือกพื้นที่ Footer1–Footer4 เพื่อเพิ่ม/จัดเรียง Widget ที่ต้องการ (Custom HTML, Categories, Social Follow ฯลฯ)' => 'Content: Go to Appearance → Widgets and select Footer1–Footer4 to add/reorder widgets (Custom HTML, Categories, Social Follow, etc.)',
    'เปิดใช้งาน Live Search (ค้นหาขณะพิมพ์)' => 'Enable Live Search (search as you type)',
    'เปิดใช้งาน Search Suggestions (Autocomplete)' => 'Enable Search Suggestions (Autocomplete)',
    'เปิดใช้งาน Table of Contents' => 'Enable Table of Contents',
    'เปิดใช้งานการค้นหา' => 'Enable search',
    'เปิดใช้งานการแชร์เนื้อหาไปยัง Social Media' => 'Enable sharing content to Social Media',
    'เปิดใช้โฆษณาแบบลอยติดด้านซ้าย (ขนาด 120x600 หรือ 160x600) แสดงเฉพาะหน้า single post' => 'Enable floating left ad (120x600 or 160x600), shown on single post only',
    'เผยแพร่เมื่อ %s' => 'Published on %s',
    'เมนู' => 'Menu',
    'เมนู (bars)' => 'Menu (bars)',
    'เมนูทางขวาของแถบ copyright: ไปที่ Appearance → Menus แล้วกำหนดเมนูให้ตำแหน่ง "Footer Copyright Menu"' => 'Menu on the right of copyright bar: Go to Appearance → Menus and assign a menu to "Footer Copyright Menu"',
    'เมื่อเลือก Social' => 'When Social is selected',
    'เลือก Fields ที่ต้องการให้ค้นหา' => 'Select fields to search',
    'เลือก Post Types ที่ต้องการให้ค้นหา' => 'Select post types to search',
    'เลือก Social Media platforms ที่ต้องการแสดงปุ่มแชร์' => 'Select Social Media platforms for share buttons',
    'เลือก widgets ที่ต้องการให้แสดงใน WordPress Widgets area (Appearance > Widgets)' => 'Select widgets to show in WordPress Widgets area (Appearance > Widgets)',
    'เลือกขนาดปุ่มแชร์' => 'Select share button size',
    'เลือกข้อมูลที่ต้องการแสดงใน Suggestions' => 'Select data to show in suggestions',
    'เลือกตำแหน่งที่ต้องการแสดง TOC' => 'Select TOC display position',
    'เลือกตำแหน่งที่ต้องการแสดง TOC บน Mobile' => 'Select TOC position on mobile',
    'เลือกตำแหน่งที่ต้องการแสดงปุ่มแชร์' => 'Select share button positions',
    'เลือกระดับ Heading ที่ต้องการแสดงใน TOC' => 'Select heading levels to show in TOC',
    'เลือกรูปแบบการแสดงผล Suggestions' => 'Select suggestions display style',
    'เลือกรูปแบบการแสดงผล TOC' => 'Select TOC display style',
    'เลือกรูปแบบการแสดงผลปุ่มแชร์' => 'Select share button display style',
    'เลือกรูปแบบการแสดงผลในหน้า Search Results' => 'Select search results layout',
    'เลือกวิธีการเรียงลำดับผลการค้นหา' => 'Select search results sort order',
    'เลือกวิธีการแสดงผลบทความในหน้าแรก: แสดง pagination หรือปุ่มโหลดข่าวเพิ่มเติม' => 'Choose how to display posts on homepage: pagination or load more button',
    'เลือกว่าจะให้กริดข่าวล่าสุดในหน้าแรกและหน้าอาร์คิฟแสดงกี่คอลัมน์ (จอขนาดกลางขึ้นไป)' => 'Choose number of columns for latest news grid on homepage and archive (medium screens and up)',
    'เลือกหมวดหมู่ที่ต้องการยกเว้นจากการค้นหา' => 'Select categories to exclude from search',
    'เลือกเดือน' => 'Select month',
    'เลือกเมนู' => 'Select menu',
    'เลือกเมนู:' => 'Select menu:',
    'เว็บตัวอย่าง:' => 'Sample site:',
    'เว้นว่าง = ใช้ชื่อเมนู (Menu) หรือหัวข้อตามคอลัมน์ (Sidebar)' => 'Leave empty to use menu name (Menu) or column heading (Sidebar)',
    'แชร์' => 'Share',
    'แชร์ (share-alt)' => 'Share (share-alt)',
    'แต่ละคอลัมน์เลือกได้ว่าจะแสดง: Widget (จาก Appearance > Widgets), Menu หรือ Social' => 'Each column can show: Widget (from Appearance > Widgets), Menu or Social',
    'แผนผัง (sitemap)' => 'Sitemap (sitemap)',
    'แสดง TOC บน Mobile' => 'Show TOC on mobile',
    'แสดง sidebar (widget) ในหน้า Archive' => 'Show sidebar (widget) on Archive pages',
    'แสดง sidebar (widget) ในหน้าแรก' => 'Show sidebar (widget) on homepage',
    'แสดง sidebar ในหน้าคงที่ (Page เช่น Privacy Policy, เกี่ยวกับเรา)' => 'Show sidebar on pages (e.g. Privacy Policy, About us)',
    'แสดง sidebar ในหน้าบทความ (Single Post)' => 'Show sidebar on single post',
    'แสดง tags ที่มาแรง (Trending tags)' => 'Show trending tags',
    'แสดง/ซ่อนหมวดย่อย' => 'Show/hide subcategories',
    'แสดงกล่องสมัครรับข่าวสาร (Newsletter) ใน footer' => 'Show newsletter subscription box in footer',
    'แสดงบทความยอดนิยมตามจำนวน views' => 'Show popular posts by views',
    'แสดงบทความล่าสุด' => 'Show recent posts',
    'แสดงปุ่มแชร์ในหน้าคงที่' => 'Show share buttons on pages',
    'แสดงปุ่มแชร์ในหน้าคงที่ (Page เช่น Privacy Policy)' => 'Show share buttons on pages (e.g. Privacy Policy)',
    'แสดงปุ่มแชร์ในหน้าบทความ' => 'Show share buttons on single post',
    'แสดงปุ่มแชร์ในหน้าบทความ (Single Post)' => 'Show share buttons on single post',
    'แสดงส่วน tags มาแรงใน footer' => 'Show trending tags section in footer',
    'แสดงหมวดย่อย' => 'Show subcategories',
    'แสดงหมายเลขหน้า' => 'Show page numbers',
    'แสดงหัวข้อ' => 'Show heading',
    'แสดงเป็น:' => 'Display as:',
    'โค้ดโฆษณา (HTML / สคริปต์ AdSense):' => 'Ad code (HTML / AdSense script):',
    'โฆษณา' => 'Ad',
    'โทรศัพท์ (phone)' => 'Phone (phone)',
    'โฟลเดอร์ (folder-open)' => 'Folder (folder-open)',
    'โหลดข่าวเพิ่มเติม' => 'Load more news',
    'ใช้สไตล์ธีม (ปรับแต่ง wp-login ให้เข้ากับธีม Chrysoberyl)' => 'Use theme style (customize wp-login to match Chrysoberyl theme)',
    'ใส่ Twitter/X username (ไม่ต้องใส่ @) เพื่อเพิ่มใน tweet' => 'Enter Twitter/X username (without @) to add to tweets',
    'ใส่อีเมลของคุณ' => 'Enter your email',
    'ไม่พบข่าว' => 'No posts found',
    'ไม่พบผลการค้นหา' => 'No search results found',
    'ไม่พบหน้า' => 'Page not found',
    'ไม่พบหน้าที่คุณกำลังมองหา' => 'The page you are looking for was not found',
    'ไม่พลาดทุกเทรนด์' => 'Never miss a trend',
    'ไม่มีหมวดหมู่' => 'No categories',
    'ไอคอนหัวข้อ:' => 'Heading icon:',
    '— ไม่มีไอคอน' => '— No icon',
    '• Widgets ที่ถูกเลือกจะแสดงใน Appearance > Widgets และสามารถเพิ่มไปยัง Widget Areas ต่างๆ ได้' => '• Selected widgets will appear in Appearance > Widgets and can be added to widget areas.',
    '• Widgets ที่ไม่ถูกเลือกจะไม่แสดงใน Widgets area แต่โค้ดยังคงทำงานอยู่' => '• Unselected widgets will not appear in Widgets area but code remains active.',
    '• การเปลี่ยนแปลงจะมีผลหลังจากบันทึกการตั้งค่า' => '• Changes take effect after saving settings.',
    '• เนื้อหาอื่น: ใส่แท็ก HTML ที่ต้องการได้ (รองรับแท็กพื้นฐาน)' => '• Other content: Add any HTML tags (basic tags supported).',
    '• แบนเนอร์รูป: ใช้ HTML เช่น' => '• Image banner: Use HTML such as',
    '• โฆษณาจาก Google AdSense: วางสคริปต์ที่ได้จาก AdSense ทั้งก้อนลงในช่องด้านบน' => '• Google AdSense: Paste the full AdSense script in the box above.',
    'หน้านี้รวมลิงก์เนื้อหาหลักของเว็บไซต์ คลิกหัวข้อแต่ละส่วนเพื่อย่อ/ขยาย' => 'This page lists the main content of the site. Click each section heading to expand or collapse.',
);

function po_escape( $s ) {
    $s = str_replace( '\\', '\\\\', $s );
    $s = str_replace( '"', '\\"', $s );
    $s = str_replace( "\n", "\\n\n", $s );
    return $s;
}

$pot = file_get_contents( $pot_file );
$pot = str_replace( '"X-Domain: chrysoberyl\n"', '"X-Domain: chrysoberyl\n"' . "\n" . '"Language: en_US\n"', $pot );

$blocks = preg_split( '/\n(?=#:)/', $pot );
$out_blocks = array();
foreach ( $blocks as $block ) {
    if ( preg_match( '/^msgid "((?:[^"\\\\]|\\\\["\\\\n])*)"\s*\nmsgstr ""\s*$/m', $block, $m ) ) {
        $msgid = stripcslashes( str_replace( array( '\\n', '\\"' ), array( "\n", '"' ), $m[1] ) );
        if ( $msgid !== '' ) {
            $trans = isset( $map[ $msgid ] ) ? $map[ $msgid ] : $msgid;
            $block = preg_replace( '/\nmsgstr ""\s*$/', "\nmsgstr \"" . po_escape( $trans ) . "\"\n", $block );
        }
    }
    $out_blocks[] = $block;
}

$out = implode( "\n", $out_blocks );
if ( strpos( $out, '"Language: en_US\n"' ) === false ) {
    $out = str_replace( '"X-Domain: chrysoberyl\n"', '"X-Domain: chrysoberyl\n"' . "\n" . '"Language: en_US\n"', $out );
}
file_put_contents( $po_file, $out );
echo "Written " . $po_file . "\n";
