<?php
/**
 * Template part for displaying Table of Contents
 *
 * @package Chrysoberyl
 * @since 1.0.0
 */

// Check if TOC is enabled (post/page option overrides theme default; Theme "Display on" restricts by type)
if ( is_singular() ) {
    $toc_show_on_post = get_option( 'chrysoberyl_toc_show_on_single_post', '1' ) === '1';
    $toc_show_on_page = get_option( 'chrysoberyl_toc_show_on_single_page', '0' ) === '1';
    if ( is_single() && ! $toc_show_on_post ) {
        return;
    }
    if ( is_page() && ! $toc_show_on_page ) {
        return;
    }
    $toc_enabled = function_exists( 'chrysoberyl_show_toc_for_post' ) ? ( chrysoberyl_show_toc_for_post( get_queried_object_id() ) ? '1' : '0' ) : get_option( 'chrysoberyl_toc_enabled', '1' );
} else {
    $toc_enabled = get_option( 'chrysoberyl_toc_enabled', '1' );
}
if ( $toc_enabled !== '1' ) {
    return;
}

// Get TOC settings
$toc_position = get_option( 'chrysoberyl_toc_position', 'top' );
$toc_mobile_enabled = get_option( 'chrysoberyl_toc_mobile_enabled', '1' );
$toc_mobile_position = get_option( 'chrysoberyl_toc_mobile_position', 'floating' );
$toc_headings = get_option( 'chrysoberyl_toc_headings', array( 'h2', 'h3', 'h4' ) );
$toc_style = get_option( 'chrysoberyl_toc_style', 'nested' );
$toc_smooth_scroll = get_option( 'chrysoberyl_toc_smooth_scroll', '1' );
$toc_scroll_spy = get_option( 'chrysoberyl_toc_scroll_spy', '1' );
$toc_collapsible = get_option( 'chrysoberyl_toc_collapsible', '1' );
$toc_sticky = get_option( 'chrysoberyl_toc_sticky', '0' );
$toc_auto_collapse_mobile = get_option( 'chrysoberyl_toc_auto_collapse_mobile', '1' );
$toc_min_headings = get_option( 'chrysoberyl_toc_min_headings', 2 );
$toc_title = get_option( 'chrysoberyl_toc_title', __( 'สารบัญ', 'chrysoberyl' ) );

// Build data attributes for JavaScript
$toc_data = array(
    'headings' => implode( ',', $toc_headings ),
    'style' => $toc_style,
    'smoothScroll' => $toc_smooth_scroll === '1',
    'scrollSpy' => false, // TOC ด้านขวาไม่แสดงสถานะ active
    'collapsible' => $toc_collapsible === '1',
    'sticky' => $toc_sticky === '1',
    'minHeadings' => absint( $toc_min_headings ),
    'title' => $toc_title,
    'mobileEnabled' => $toc_mobile_enabled === '1',
    'mobilePosition' => $toc_mobile_position,
    'autoCollapseMobile' => $toc_auto_collapse_mobile === '1',
);

$toc_classes = array(
    'chrysoberyl-toc',
    'chrysoberyl-toc-' . esc_attr( $toc_position ),
    'chrysoberyl-toc-style-' . esc_attr( $toc_style ),
);

if ( $toc_sticky === '1' ) {
    $toc_classes[] = 'chrysoberyl-toc-sticky';
}

if ( $toc_collapsible === '1' ) {
    $toc_classes[] = 'chrysoberyl-toc-collapsible';
}

if ( $toc_mobile_enabled === '1' ) {
    $toc_classes[] = 'chrysoberyl-toc-mobile-' . esc_attr( $toc_mobile_position );
}

if ( $toc_auto_collapse_mobile === '1' ) {
    $toc_classes[] = 'chrysoberyl-toc-auto-collapse-mobile';
}
?>

<div class="<?php echo esc_attr( implode( ' ', $toc_classes ) ); ?>" 
     data-toc-config='<?php echo esc_attr( json_encode( $toc_data ) ); ?>'>
    <div class="chrysoberyl-toc-container">
        <?php if ( $toc_collapsible === '1' ) : ?>
            <button type="button" class="chrysoberyl-toc-toggle" aria-label="<?php echo esc_attr( $toc_title ); ?>">
                <span class="chrysoberyl-toc-title">
                    <i class="fas fa-list-ul"></i>
                    <?php echo esc_html( $toc_title ); ?>
                </span>
                <i class="fas fa-chevron-down chrysoberyl-toc-icon"></i>
            </button>
        <?php else : ?>
            <div class="chrysoberyl-toc-header">
                <h3 class="chrysoberyl-toc-title">
                    <i class="fas fa-list-ul"></i>
                    <?php echo esc_html( $toc_title ); ?>
                </h3>
            </div>
        <?php endif; ?>
        
        <div class="chrysoberyl-toc-content">
            <nav class="chrysoberyl-toc-nav" role="navigation" aria-label="<?php echo esc_attr( $toc_title ); ?>">
                <!-- TOC will be generated by JavaScript -->
            </nav>
        </div>
    </div>
</div>

<?php if ( $toc_mobile_enabled === '1' && $toc_mobile_position === 'floating' ) : ?>
    <!-- Mobile Floating TOC Button -->
    <button class="chrysoberyl-toc-mobile-toggle fixed bottom-20 left-4 z-40 bg-accent text-white w-14 h-14 rounded-full shadow-lg flex items-center justify-center hover:bg-blue-600 transition md:hidden" 
            aria-label="<?php echo esc_attr( $toc_title ); ?>">
        <i class="fas fa-list text-xl"></i>
    </button>
    
    <!-- Mobile TOC Drawer -->
    <div class="chrysoberyl-toc-mobile-drawer fixed inset-0 z-50 bg-black/50 backdrop-blur-sm hidden md:hidden">
        <div class="chrysoberyl-toc-mobile-content bg-white h-full w-80 max-w-[85vw] shadow-2xl transform transition-transform">
            <div class="flex items-center justify-between p-4 border-b border-gray-200">
                <h3 class="font-bold text-lg"><?php echo esc_html( $toc_title ); ?></h3>
                <button class="chrysoberyl-toc-mobile-close w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center text-gray-500 hover:bg-gray-200 transition">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="chrysoberyl-toc-mobile-nav p-4 overflow-y-auto h-[calc(100%-65px)]">
                <!-- TOC will be generated by JavaScript -->
            </div>
        </div>
    </div>
<?php endif; ?>
